//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orderbox.Core.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistrationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orderbox.Core.Resources.Account.RegistrationResource", typeof(RegistrationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akun anda sudah diaktifkan. Silahkan masuk melalui halaman login..
        /// </summary>
        public static string ActivationSuccessMessage {
            get {
                return ResourceManager.GetString("ActivationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivasi Berhasil!.
        /// </summary>
        public static string ActivationSuccessTitle {
            get {
                return ResourceManager.GetString("ActivationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your administrator to re-send the activation url.
        /// </summary>
        public static string AgentActivationInvalidMessage {
            get {
                return ResourceManager.GetString("AgentActivationInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Activation Url.
        /// </summary>
        public static string AgentActivationInvalidTitle {
            get {
                return ResourceManager.GetString("AgentActivationInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Usaha.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain sudah digunakan.
        /// </summary>
        public static string DomainExistErrorMessage {
            get {
                return ResourceManager.GetString("DomainExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alamat Email.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sudah terdaftar. Silahkan gunakan alamat email lainnya..
        /// </summary>
        public static string EmailAddressHasBeenUsed {
            get {
                return ResourceManager.GetString("EmailAddressHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email belum terdaftar..
        /// </summary>
        public static string EmailNotRegistered {
            get {
                return ResourceManager.GetString("EmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Depan.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrasi tidak valid..
        /// </summary>
        public static string InvalidRegistration {
            get {
                return ResourceManager.GetString("InvalidRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kesalahan kode token atau token sudah kadaluarsa. Silahkan mengulangi proses pendaftaran..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Belakang.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudah mempunyai akun?.
        /// </summary>
        public static string SignInOfferMessage {
            get {
                return ResourceManager.GetString("SignInOfferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;Nama situs harus tanpa spasi&lt;/li&gt;&lt;li&gt;Nama situs tidak boleh meggunakan karakter lain selain angka, huruf dan tanda -&lt;/li&gt;&lt;li&gt;Nama situs harus diawali dengan angka atau huruf dan diakhiri oleh angka atau huruf juga&lt;/li&gt;&lt;li&gt;Nama situs harus terdiri dari 3 sampai dengan 18 karakter&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string SubDomainErrorFormatMessage {
            get {
                return ResourceManager.GetString("SubDomainErrorFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alamat situs yang diinginkan.
        /// </summary>
        public static string TenantDomain {
            get {
                return ResourceManager.GetString("TenantDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contoh: tokosubur.
        /// </summary>
        public static string TenantDomain_Description {
            get {
                return ResourceManager.GetString("TenantDomain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona Waktu.
        /// </summary>
        public static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kode Verifikasi.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
    }
}
