//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orderbox.Core.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orderbox.Core.Resources.Common.BankResource", typeof(BankResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank BCA.
        /// </summary>
        public static string Bca {
            get {
                return ResourceManager.GetString("Bca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank BNI.
        /// </summary>
        public static string Bni {
            get {
                return ResourceManager.GetString("Bni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank BPD Bali.
        /// </summary>
        public static string BpdBali {
            get {
                return ResourceManager.GetString("BpdBali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank BRI.
        /// </summary>
        public static string Bri {
            get {
                return ResourceManager.GetString("Bri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank BTN.
        /// </summary>
        public static string Btn {
            get {
                return ResourceManager.GetString("Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank BTPN.
        /// </summary>
        public static string Btpn {
            get {
                return ResourceManager.GetString("Btpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank CIMB Niaga.
        /// </summary>
        public static string CimbNiaga {
            get {
                return ResourceManager.GetString("CimbNiaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Danamon.
        /// </summary>
        public static string Danamon {
            get {
                return ResourceManager.GetString("Danamon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Mandiri.
        /// </summary>
        public static string Mandiri {
            get {
                return ResourceManager.GetString("Mandiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Maybank.
        /// </summary>
        public static string Maybank {
            get {
                return ResourceManager.GetString("Maybank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Mega.
        /// </summary>
        public static string Mega {
            get {
                return ResourceManager.GetString("Mega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank OCBC NISP.
        /// </summary>
        public static string OcbcNisp {
            get {
                return ResourceManager.GetString("OcbcNisp", resourceCulture);
            }
        }
    }
}
