//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orderbox.Core.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orderbox.Core.Resources.Common.OrderResource", typeof(OrderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alamat Pengiriman.
        /// </summary>
        public static string BuyerAddress {
            get {
                return ResourceManager.GetString("BuyerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Pembeli.
        /// </summary>
        public static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Telepon.
        /// </summary>
        public static string BuyerPhone {
            get {
                return ResourceManager.GetString("BuyerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memesan {0} produk.  .
        /// </summary>
        public static string NewOrderNotificationBody {
            get {
                return ResourceManager.GetString("NewOrderNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halo, saya sudah melakukan pemesanan dengan nomor order {0}  {1} , mohon diproses.
        /// </summary>
        public static string NotifySellerChatText {
            get {
                return ResourceManager.GetString("NotifySellerChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Pesanan.
        /// </summary>
        public static string Order_Status {
            get {
                return ResourceManager.GetString("Order_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayar di Tempat.
        /// </summary>
        public static string Payment_Cod {
            get {
                return ResourceManager.GetString("Payment_Cod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Bank.
        /// </summary>
        public static string Payment_Transfer {
            get {
                return ResourceManager.GetString("Payment_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apakah anda menerima bukti pembayaran ini?.
        /// </summary>
        public static string PaymentProof_AcceptConfirmationMessage {
            get {
                return ResourceManager.GetString("PaymentProof_AcceptConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apakah anda ingin menolak bukti pembayaran ini?.
        /// </summary>
        public static string PaymentProof_RejectConfirmationMessage {
            get {
                return ResourceManager.GetString("PaymentProof_RejectConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apakah anda ingin pembeli mengunggah ulang bukti pembayarannya?.
        /// </summary>
        public static string PaymentProof_ResetConfirmationMessage {
            get {
                return ResourceManager.GetString("PaymentProof_ResetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string PaymentStatus_Cancelled {
            get {
                return ResourceManager.GetString("PaymentStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string PaymentStatus_Expired {
            get {
                return ResourceManager.GetString("PaymentStatus_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string PaymentStatus_Paid {
            get {
                return ResourceManager.GetString("PaymentStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string PaymentStatus_Ready {
            get {
                return ResourceManager.GetString("PaymentStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terima kasih telah berbelanja. Silahkan klik link berikut untuk melihat nota belanja anda: {0}.
        /// </summary>
        public static string SendInvoiceText {
            get {
                return ResourceManager.GetString("SendInvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batal.
        /// </summary>
        public static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selesai.
        /// </summary>
        public static string Status_Finish {
            get {
                return ResourceManager.GetString("Status_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diproses.
        /// </summary>
        public static string Status_InProgress {
            get {
                return ResourceManager.GetString("Status_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baru.
        /// </summary>
        public static string Status_New {
            get {
                return ResourceManager.GetString("Status_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikirim.
        /// </summary>
        public static string Status_Sent {
            get {
                return ResourceManager.GetString("Status_Sent", resourceCulture);
            }
        }
    }
}
