//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orderbox.Core.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orderbox.Core.Resources.Common.ReportResource", typeof(ReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik Omzet per Hari.
        /// </summary>
        public static string DailyRevenueChart {
            get {
                return ResourceManager.GetString("DailyRevenueChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Laporan.
        /// </summary>
        public static string DownloadReport {
            get {
                return ResourceManager.GetString("DownloadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dari Tanggal.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produk Terlaris.
        /// </summary>
        public static string PopularProduct {
            get {
                return ResourceManager.GetString("PopularProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah Penjualan.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laporan.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omzet.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daftar Produk Terjual.
        /// </summary>
        public static string SoldItemList {
            get {
                return ResourceManager.GetString("SoldItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampai Tanggal.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produk dengan omzet tertinggi.
        /// </summary>
        public static string TopRevenueProduct {
            get {
                return ResourceManager.GetString("TopRevenueProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pesanan Batal.
        /// </summary>
        public static string TotalOrderCancelledSummary {
            get {
                return ResourceManager.GetString("TotalOrderCancelledSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pesanan Selesai.
        /// </summary>
        public static string TotalOrderFinishedSummary {
            get {
                return ResourceManager.GetString("TotalOrderFinishedSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pesanan.
        /// </summary>
        public static string TotalOrderSummary {
            get {
                return ResourceManager.GetString("TotalOrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Penjualan.
        /// </summary>
        public static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
    }
}
