//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orderbox.Core.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TenantResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TenantResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orderbox.Core.Resources.Common.TenantResource", typeof(TenantResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Pemilik Akun.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomor Rekening.
        /// </summary>
        public static string AccountNumberBank {
            get {
                return ResourceManager.GetString("AccountNumberBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomor Handphone.
        /// </summary>
        public static string AccountNumberWallet {
            get {
                return ResourceManager.GetString("AccountNumberWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Bank.
        /// </summary>
        public static string AccountProviderBank {
            get {
                return ResourceManager.GetString("AccountProviderBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Penyedia Layanan.
        /// </summary>
        public static string AccountProviderWallet {
            get {
                return ResourceManager.GetString("AccountProviderWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasi Tambahan.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoh: jam operational toko, waktu deliveri produk, dan sebagainya..
        /// </summary>
        public static string AdditionalInformationPlaceholder {
            get {
                return ResourceManager.GetString("AdditionalInformationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alamat.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to access category.
        /// </summary>
        public static string AllowToAccessCategory {
            get {
                return ResourceManager.GetString("AllowToAccessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to access checkout setting.
        /// </summary>
        public static string AllowToAccessCheckoutSetting {
            get {
                return ResourceManager.GetString("AllowToAccessCheckoutSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to access product.
        /// </summary>
        public static string AllowToAccessProduct {
            get {
                return ResourceManager.GetString("AllowToAccessProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to access profile.
        /// </summary>
        public static string AllowToAccessProfile {
            get {
                return ResourceManager.GetString("AllowToAccessProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Form.
        /// </summary>
        public static string CheckoutForm {
            get {
                return ResourceManager.GetString("CheckoutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Registration Link.
        /// </summary>
        public static string CopyRegistrationLink {
            get {
                return ResourceManager.GetString("CopyRegistrationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negara.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer harus login.
        /// </summary>
        public static string CustomerMustLogin {
            get {
                return ResourceManager.GetString("CustomerMustLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google OAuth Client Id.
        /// </summary>
        public static string GoogleOAuthClientId {
            get {
                return ResourceManager.GetString("GoogleOAuthClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Transfer.
        /// </summary>
        public static string OptionCodeBank {
            get {
                return ResourceManager.GetString("OptionCodeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Inquiry.
        /// </summary>
        public static string OptionCodeCheckoutFormSimpleInquiry {
            get {
                return ResourceManager.GetString("OptionCodeCheckoutFormSimpleInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayar di Tempat (COD).
        /// </summary>
        public static string OptionCodeCod {
            get {
                return ResourceManager.GetString("OptionCodeCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Gateway.
        /// </summary>
        public static string OptionCodePaymentGateway {
            get {
                return ResourceManager.GetString("OptionCodePaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dompet Digital.
        /// </summary>
        public static string OptionCodeWallet {
            get {
                return ResourceManager.GetString("OptionCodeWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Duration (in Minutes) *.
        /// </summary>
        public static string PaymentGatewayMinuteDuration {
            get {
                return ResourceManager.GetString("PaymentGatewayMinuteDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string PaymentGatewayProvider {
            get {
                return ResourceManager.GetString("PaymentGatewayProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key.
        /// </summary>
        public static string PaymentGatewayProviderApiKey {
            get {
                return ResourceManager.GetString("PaymentGatewayProviderApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Hook Validation Secret.
        /// </summary>
        public static string PaymentGatewayProviderWebHookSecret {
            get {
                return ResourceManager.GetString("PaymentGatewayProviderWebHookSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenis Pembayaran.
        /// </summary>
        public static string PaymentOption {
            get {
                return ResourceManager.GetString("PaymentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomor Hp/Whatsapp.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop active.
        /// </summary>
        public static string ShopActive {
            get {
                return ResourceManager.GetString("ShopActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant id is required.
        /// </summary>
        public static string TenantIdIsRequired {
            get {
                return ResourceManager.GetString("TenantIdIsRequired", resourceCulture);
            }
        }
    }
}
