//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Core.Resources.GeneralResource", typeof(GeneralResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file name specified..
        /// </summary>
        public static string Assets_NoFileNameSpecified {
            get {
                return ResourceManager.GetString("Assets_NoFileNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penyimpanan Data Gagal.
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terima.
        /// </summary>
        public static string General_Accept {
            get {
                return ResourceManager.GetString("General_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akses ditolak.
        /// </summary>
        public static string General_AccessDenied {
            get {
                return ResourceManager.GetString("General_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivasi.
        /// </summary>
        public static string General_Activate {
            get {
                return ResourceManager.GetString("General_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string General_Active {
            get {
                return ResourceManager.GetString("General_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tambah.
        /// </summary>
        public static string General_Add {
            get {
                return ResourceManager.GetString("General_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsip.
        /// </summary>
        public static string General_Archive {
            get {
                return ResourceManager.GetString("General_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batal.
        /// </summary>
        public static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutup.
        /// </summary>
        public static string General_Close {
            get {
                return ResourceManager.GetString("General_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmasi.
        /// </summary>
        public static string General_Confirm {
            get {
                return ResourceManager.GetString("General_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Link.
        /// </summary>
        public static string General_CopyLink {
            get {
                return ResourceManager.GetString("General_CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tambah.
        /// </summary>
        public static string General_Create {
            get {
                return ResourceManager.GetString("General_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapus.
        /// </summary>
        public static string General_Delete {
            get {
                return ResourceManager.GetString("General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakin ingin menghapus data ini?.
        /// </summary>
        public static string General_DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("General_DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data yang sudah dihapus tidak dapat dikembalikan!.
        /// </summary>
        public static string General_DeleteWarning {
            get {
                return ResourceManager.GetString("General_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string General_Download {
            get {
                return ResourceManager.GetString("General_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value bigger than {1}.
        /// </summary>
        public static string General_EnterValueBiggerThan {
            get {
                return ResourceManager.GetString("General_EnterValueBiggerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string General_Forbidden {
            get {
                return ResourceManager.GetString("General_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak aktif.
        /// </summary>
        public static string General_Inactive {
            get {
                return ResourceManager.GetString("General_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invitation.
        /// </summary>
        public static string General_Invitation {
            get {
                return ResourceManager.GetString("General_Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak.
        /// </summary>
        public static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolak.
        /// </summary>
        public static string General_Reject {
            get {
                return ResourceManager.GetString("General_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirim Ulang.
        /// </summary>
        public static string General_Resend {
            get {
                return ResourceManager.GetString("General_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpan.
        /// </summary>
        public static string General_Save {
            get {
                return ResourceManager.GetString("General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Invite.
        /// </summary>
        public static string General_SaveAndInvite {
            get {
                return ResourceManager.GetString("General_SaveAndInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirim.
        /// </summary>
        public static string General_Send {
            get {
                return ResourceManager.GetString("General_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masuk.
        /// </summary>
        public static string General_SignIn {
            get {
                return ResourceManager.GetString("General_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keluar.
        /// </summary>
        public static string General_SignOut {
            get {
                return ResourceManager.GetString("General_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daftar.
        /// </summary>
        public static string General_SignUp {
            get {
                return ResourceManager.GetString("General_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string General_Submit {
            get {
                return ResourceManager.GetString("General_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string General_Update {
            get {
                return ResourceManager.GetString("General_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string General_View {
            get {
                return ResourceManager.GetString("General_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya.
        /// </summary>
        public static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya, Hapus!.
        /// </summary>
        public static string General_YesDeleteIt {
            get {
                return ResourceManager.GetString("General_YesDeleteIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data berhasil dihapus.
        /// </summary>
        public static string Info_Deleted {
            get {
                return ResourceManager.GetString("Info_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data berhasil tersimpan.
        /// </summary>
        public static string Info_Saved {
            get {
                return ResourceManager.GetString("Info_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item tidak ditemukan.
        /// </summary>
        public static string Item_Delete_NotFound {
            get {
                return ResourceManager.GetString("Item_Delete_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item yang anda cari tidak ditemukan.
        /// </summary>
        public static string Item_NotFound {
            get {
                return ResourceManager.GetString("Item_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item tidak ditemukan.
        /// </summary>
        public static string Item_Update_NotFound {
            get {
                return ResourceManager.GetString("Item_Update_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak mendapatkan ijin.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
